version: '1.0'

volumes:
  postgres_data: {}

services:
  back:
    container_name: back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: password

  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: avito_db
    volumes:
      - postgres_data:/var/lib/postgres
    ports:
      - '5435:5435'
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready -U test_user -d test_db
      interval: 10s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"

  db_migrate:
    image: migrate/migrate
    container_name: db_migrate
    restart: on-failure
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://test_user:password@db/test_db?sslmode=disable", "up"]
    depends_on:
      - db
